# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\lyceum\2god\project\project.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l_image = QtWidgets.QLabel(self.centralwidget)
        self.l_image.setGeometry(QtCore.QRect(370, 100, 401, 531))
        self.l_image.setText("")
        self.l_image.setObjectName("l_image")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 40, 782, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.new_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.new_2.setObjectName("new_2")
        self.gridLayout.addWidget(self.new_2, 0, 8, 1, 1)
        self.dell = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.dell.setObjectName("dell")
        self.gridLayout.addWidget(self.dell, 1, 8, 1, 1)
        self.grad = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.grad.setObjectName("grad")
        self.gridLayout.addWidget(self.grad, 0, 2, 1, 1)
        self.right = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.right.setObjectName("right")
        self.gridLayout.addWidget(self.right, 1, 6, 1, 1)
        self.gaus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.gaus.setObjectName("gaus")
        self.gridLayout.addWidget(self.gaus, 0, 4, 1, 1)
        self.left = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.left.setToolTipDuration(-1)
        self.left.setObjectName("left")
        self.gridLayout.addWidget(self.left, 0, 6, 1, 1)
        self.rgbgrad = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.rgbgrad.setObjectName("rgbgrad")
        self.gridLayout.addWidget(self.rgbgrad, 1, 2, 1, 1)
        self.rgbsave = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.rgbsave.setObjectName("rgbsave")
        self.gridLayout.addWidget(self.rgbsave, 1, 5, 1, 1)
        self.save = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 1, 7, 1, 1)
        self.rgdel = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.rgdel.setObjectName("rgdel")
        self.gridLayout.addWidget(self.rgdel, 0, 5, 1, 1)
        self.fix = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.fix.setObjectName("fix")
        self.gridLayout.addWidget(self.fix, 0, 7, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 311, 51))
        self.groupBox.setObjectName("groupBox")
        self.cmb_genres = QtWidgets.QComboBox(self.groupBox)
        self.cmb_genres.setGeometry(QtCore.QRect(0, 20, 211, 20))
        self.cmb_genres.setObjectName("cmb_genres")
        self.im_table = QtWidgets.QTableView(self.centralwidget)
        self.im_table.setGeometry(QtCore.QRect(0, 100, 481, 531))
        self.im_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.im_table.setObjectName("im_table")
        self.b_new_genre = QtWidgets.QPushButton(self.centralwidget)
        self.b_new_genre.setGeometry(QtCore.QRect(220, 20, 87, 23))
        self.b_new_genre.setObjectName("b_new_genre")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.new_2.setText(_translate("MainWindow", "Добавить картинку"))
        self.dell.setText(_translate("MainWindow", "Удалить картинку"))
        self.grad.setText(_translate("MainWindow", "Гралиент"))
        self.right.setText(_translate("MainWindow", "90 градусов ->"))
        self.gaus.setText(_translate("MainWindow", "Фильтер Гауса"))
        self.left.setText(_translate("MainWindow", "<-90 градусов"))
        self.save.setText(_translate("MainWindow", "сохранить измения"))
        self.rgdel.setText(_translate("MainWindow", "Оставить 1 цветовой канал"))
        self.fix.setText(_translate("MainWindow", "Отредактирывать картинку"))
        self.groupBox.setTitle(_translate("MainWindow", "Жанры"))
        self.b_new_genre.setText(_translate("MainWindow", "Добавить жанр"))
        self.action_3.setText(_translate("MainWindow", "ьлдьд"))
        self.action_4.setText(_translate("MainWindow", "ь лщлщз"))
