import requests
import datetime as DT
from dateutil import parser
import locale
locale.setlocale(locale.LC_ALL, "ru")


def get_coordinates(toponym_to_find):
    geocoder_api_server = "http://geocode-maps.yandex.ru/1.x/"

    geocoder_params = {
        "apikey": "40d1649f-0493-4b70-98ba-98533de7710b",
        "geocode": toponym_to_find,
        "format": "json"}

    response = requests.get(geocoder_api_server, params=geocoder_params)

    json_response = response.json()
    if json_response["response"]["GeoObjectCollection"]["featureMember"]:
        toponym = json_response["response"]["GeoObjectCollection"]["featureMember"][0]["GeoObject"]
    else:
        return None
    toponym_coodrinates = toponym["Point"]["pos"]
    toponym_longitude, toponym_lattitude = toponym_coodrinates.split(" ")

    return toponym_lattitude, toponym_longitude


def get_pogoda(place):
    APIKEY = "3151d868-62ec-4452-9374-c10e411dd8d0"
    weather_api_server = "https://api.weather.yandex.ru/v1/forecast"
    lat, lon = get_coordinates(place)
    params = {
        "lat": lat,
        "lon": lon,
        "extra": "true"}

    response = requests.get(weather_api_server, params=params, headers={"X-Yandex-API-Key": APIKEY})
    return response.json()

print(get_pogoda('Калуга'))

test = {'now': 1589292322, 'now_dt': '2020-05-12T14:05:22.069Z',
        'info': {'f': True, 'n': True, 'nr': True, 'ns': True, 'nsr': True, 'p': True, 'lat': 54.513845,
                 'lon': 36.261215, 'tzinfo': {'name': 'Europe/Moscow', 'abbr': 'MSK', 'offset': 10800, 'dst': False},
                 'def_pressure_mm': 743, 'def_pressure_pa': 990, '_h': False,
                 'url': 'https://yandex.ru/pogoda/?lat=54.513845&lon=36.261215'},
        'fact': {'temp': 16, 'feels_like': 13, 'icon': 'bkn_ra_d', 'condition': 'partly-cloudy-and-rain',
                 'wind_speed': 6, 'wind_gust': 12.3, 'wind_dir': 'sw', 'pressure_mm': 730, 'pressure_pa': 974,
                 'humidity': 88, 'uv_index': 1, 'soil_temp': 17, 'soil_moisture': 0.28, 'daytime': 'd', 'polar': False,
                 'season': 'spring', 'obs_time': 1589291551, 'accum_prec': {'1': 2.4, '3': 7.5, '7': 16},
                 'source': 'station'}, 'forecasts': [
        {'date': '2020-05-12', 'date_ts': 1589230800, 'week': 20, 'sunrise': '04:34', 'sunset': '20:29',
         'rise_begin': '03:48', 'set_end': '21:15', 'moon_code': 3, 'moon_text': 'decreasing-moon', 'parts': {
            'night': {'_source': '0,1,2,3,4,5', 'temp_min': 12, 'temp_max': 13, 'temp_avg': 13, 'feels_like': 9,
                      'icon': 'skc_n', 'condition': 'clear', 'daytime': 'n', 'polar': False, 'wind_speed': 3.6,
                      'wind_gust': 8.7, 'wind_dir': 's', 'pressure_mm': 735, 'pressure_pa': 980, 'humidity': 60,
                      'uv_index': 0, 'soil_temp': 12, 'soil_moisture': 0.3, 'prec_mm': 0, 'prec_period': 360,
                      'prec_prob': 0},
            'morning': {'_source': '6,7,8,9,10,11', 'temp_min': 13, 'temp_max': 20, 'temp_avg': 17, 'feels_like': 13,
                        'icon': 'bkn_d', 'condition': 'cloudy', 'daytime': 'd', 'polar': False, 'wind_speed': 5.6,
                        'wind_gust': 13.3, 'wind_dir': 's', 'pressure_mm': 733, 'pressure_pa': 978, 'humidity': 54,
                        'uv_index': 4, 'soil_temp': 13, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 360,
                        'prec_prob': 0},
            'day': {'_source': '12,13,14,15,16,17', 'temp_min': 16, 'temp_max': 21, 'temp_avg': 19, 'feels_like': 15,
                    'icon': 'ovc_ra', 'condition': 'cloudy-and-rain', 'daytime': 'd', 'polar': False, 'wind_speed': 6.3,
                    'wind_gust': 14.7, 'wind_dir': 's', 'pressure_mm': 731, 'pressure_pa': 975, 'humidity': 60,
                    'uv_index': 2, 'soil_temp': 17, 'soil_moisture': 0.28, 'prec_mm': 3.7, 'prec_period': 360,
                    'prec_prob': 80},
            'evening': {'_source': '18,19,20,21,22,23', 'temp_min': 9, 'temp_max': 15, 'temp_avg': 12, 'feels_like': 8,
                        'icon': 'ovc_-ra', 'condition': 'overcast-and-light-rain', 'daytime': 'd', 'polar': False,
                        'wind_speed': 5.5, 'wind_gust': 12.5, 'wind_dir': 's', 'pressure_mm': 729, 'pressure_pa': 972,
                        'humidity': 86, 'uv_index': 0, 'soil_temp': 15, 'soil_moisture': 0.29, 'prec_mm': 0.4,
                        'prec_period': 360, 'prec_prob': 80},
            'day_short': {'_source': '8,9,10,11,12,13,14,15,16,17,18,19,20', 'temp': 21, 'temp_min': 14,
                          'feels_like': 18, 'icon': 'ovc_ra', 'condition': 'cloudy-and-rain', 'wind_speed': 6.3,
                          'wind_gust': 14.7, 'wind_dir': 's', 'pressure_mm': 731, 'pressure_pa': 975, 'humidity': 63,
                          'uv_index': 2, 'soil_temp': 15, 'soil_moisture': 0.29, 'prec_mm': 3.8, 'prec_prob': 80},
            'night_short': {'temp': 12, 'feels_like': 8, 'icon': 'skc_n', 'condition': 'clear', 'wind_speed': 3.6,
                            'wind_gust': 8.7, 'wind_dir': 's', 'pressure_mm': 735, 'pressure_pa': 980, 'humidity': 60,
                            'uv_index': 0, 'soil_temp': 12, 'soil_moisture': 0.3, 'prec_mm': 0, 'prec_prob': 0}},
         'hours': [
             {'hour': '0', 'hour_ts': 1589230800, 'temp': 13, 'feels_like': 10, 'icon': 'skc_n', 'condition': 'clear',
              'wind_speed': 2.7, 'wind_gust': 7.4, 'wind_dir': 's', 'pressure_mm': 736, 'pressure_pa': 982,
              'humidity': 57, 'uv_index': 0, 'soil_temp': 12, 'soil_moisture': 0.3, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '1', 'hour_ts': 1589234400, 'temp': 13, 'feels_like': 10, 'icon': 'skc_n', 'condition': 'clear',
              'wind_speed': 3.1, 'wind_gust': 7.4, 'wind_dir': 's', 'pressure_mm': 736, 'pressure_pa': 982,
              'humidity': 60, 'uv_index': 0, 'soil_temp': 12, 'soil_moisture': 0.3, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '2', 'hour_ts': 1589238000, 'temp': 12, 'feels_like': 9, 'icon': 'skc_n', 'condition': 'clear',
              'wind_speed': 3, 'wind_gust': 7.4, 'wind_dir': 's', 'pressure_mm': 736, 'pressure_pa': 982,
              'humidity': 61, 'uv_index': 0, 'soil_temp': 12, 'soil_moisture': 0.3, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '3', 'hour_ts': 1589241600, 'temp': 13, 'feels_like': 10, 'icon': 'skc_n', 'condition': 'clear',
              'wind_speed': 3.1, 'wind_gust': 8.7, 'wind_dir': 's', 'pressure_mm': 735, 'pressure_pa': 980,
              'humidity': 60, 'uv_index': 0, 'soil_temp': 11, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '4', 'hour_ts': 1589245200, 'temp': 12, 'feels_like': 8, 'icon': 'skc_n', 'condition': 'clear',
              'wind_speed': 3.6, 'wind_gust': 8.7, 'wind_dir': 's', 'pressure_mm': 734, 'pressure_pa': 979,
              'humidity': 62, 'uv_index': 0, 'soil_temp': 11, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '5', 'hour_ts': 1589248800, 'temp': 12, 'feels_like': 8, 'icon': 'skc_d', 'condition': 'clear',
              'wind_speed': 3.6, 'wind_gust': 8.7, 'wind_dir': 's', 'pressure_mm': 734, 'pressure_pa': 979,
              'humidity': 62, 'uv_index': 0, 'soil_temp': 11, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '6', 'hour_ts': 1589252400, 'temp': 13, 'feels_like': 9, 'icon': 'skc_d', 'condition': 'clear',
              'wind_speed': 3.9, 'wind_gust': 10.3, 'wind_dir': 's', 'pressure_mm': 734, 'pressure_pa': 979,
              'humidity': 59, 'uv_index': 0, 'soil_temp': 11, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '7', 'hour_ts': 1589256000, 'temp': 15, 'feels_like': 11, 'icon': 'skc_d', 'condition': 'clear',
              'wind_speed': 4.7, 'wind_gust': 10.3, 'wind_dir': 's', 'pressure_mm': 734, 'pressure_pa': 979,
              'humidity': 58, 'uv_index': 1, 'soil_temp': 11, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '8', 'hour_ts': 1589259600, 'temp': 17, 'feels_like': 13, 'icon': 'skc_d', 'condition': 'clear',
              'wind_speed': 4.8, 'wind_gust': 10.3, 'wind_dir': 's', 'pressure_mm': 733, 'pressure_pa': 978,
              'humidity': 55, 'uv_index': 1, 'soil_temp': 11, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '9', 'hour_ts': 1589263200, 'temp': 18, 'feels_like': 14, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 5.6, 'wind_gust': 13.3, 'wind_dir': 's', 'pressure_mm': 732, 'pressure_pa': 976,
              'humidity': 53, 'uv_index': 2, 'soil_temp': 14, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '10', 'hour_ts': 1589266800, 'temp': 19, 'feels_like': 15, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 5.6, 'wind_gust': 12.2, 'wind_dir': 's', 'pressure_mm': 732, 'pressure_pa': 976,
              'humidity': 51, 'uv_index': 3, 'soil_temp': 14, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '11', 'hour_ts': 1589270400, 'temp': 20, 'feels_like': 17, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 5.6, 'wind_gust': 12.2, 'wind_dir': 's', 'pressure_mm': 732, 'pressure_pa': 976,
              'humidity': 50, 'uv_index': 4, 'soil_temp': 14, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '12', 'hour_ts': 1589274000, 'temp': 21, 'feels_like': 18, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 5.8, 'wind_gust': 14.7, 'wind_dir': 's', 'pressure_mm': 731, 'pressure_pa': 975,
              'humidity': 48, 'uv_index': 4, 'soil_temp': 17, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '13', 'hour_ts': 1589277600, 'temp': 21, 'feels_like': 17, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 6.3, 'wind_gust': 14.7, 'wind_dir': 's', 'pressure_mm': 731, 'pressure_pa': 975,
              'humidity': 51, 'uv_index': 1, 'soil_temp': 17, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '14', 'hour_ts': 1589281200, 'temp': 20, 'feels_like': 16, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 6.2, 'wind_gust': 14.7, 'wind_dir': 's', 'pressure_mm': 731, 'pressure_pa': 975,
              'humidity': 52, 'uv_index': 1, 'soil_temp': 17, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0}, {'hour': '15', 'hour_ts': 1589284800, 'temp': 17, 'feels_like': 14, 'icon': 'ovc_ra',
                                'condition': 'cloudy-and-rain', 'wind_speed': 4.9, 'wind_gust': 12.3, 'wind_dir': 's',
                                'pressure_mm': 730, 'pressure_pa': 974, 'humidity': 66, 'uv_index': 1, 'soil_temp': 17,
                                'soil_moisture': 0.28, 'prec_mm': 1.5, 'prec_period': 60, 'prec_prob': 60,
                                '_nowcast': True},
             {'hour': '16', 'hour_ts': 1589288400, 'temp': 17, 'feels_like': 14, 'icon': 'ovc_ra',
              'condition': 'cloudy-and-rain', 'wind_speed': 5.5, 'wind_gust': 12.3, 'wind_dir': 's', 'pressure_mm': 730,
              'pressure_pa': 974, 'humidity': 69, 'uv_index': 1, 'soil_temp': 17, 'soil_moisture': 0.28, 'prec_mm': 1.7,
              'prec_period': 60, 'prec_prob': 80, '_nowcast': True},
             {'hour': '17', 'hour_ts': 1589292000, 'temp': 16, 'feels_like': 12, 'icon': 'ovc_ra',
              'condition': 'cloudy-and-rain', 'wind_speed': 5.4, 'wind_gust': 12.3, 'wind_dir': 's', 'pressure_mm': 730,
              'pressure_pa': 974, 'humidity': 71, 'uv_index': 1, 'soil_temp': 17, 'soil_moisture': 0.28, 'prec_mm': 0.5,
              'prec_period': 60, 'prec_prob': 60, '_nowcast': True},
             {'hour': '18', 'hour_ts': 1589295600, 'temp': 15, 'feels_like': 12, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 5, 'wind_gust': 12.5, 'wind_dir': 's', 'pressure_mm': 729, 'pressure_pa': 972,
              'humidity': 82, 'uv_index': 0, 'soil_temp': 15, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0, '_nowcast': True},
             {'hour': '19', 'hour_ts': 1589299200, 'temp': 15, 'feels_like': 12, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 5.2, 'wind_gust': 12.5, 'wind_dir': 's', 'pressure_mm': 729, 'pressure_pa': 972,
              'humidity': 83, 'uv_index': 0, 'soil_temp': 15, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0, '_nowcast': True},
             {'hour': '20', 'hour_ts': 1589302800, 'temp': 14, 'feels_like': 11, 'icon': 'ovc_-ra',
              'condition': 'overcast-and-light-rain', 'wind_speed': 5.1, 'wind_gust': 12.5, 'wind_dir': 's',
              'pressure_mm': 729, 'pressure_pa': 972, 'humidity': 84, 'uv_index': 0, 'soil_temp': 15,
              'soil_moisture': 0.29, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 80},
             {'hour': '21', 'hour_ts': 1589306400, 'temp': 13, 'feels_like': 10, 'icon': 'ovc_-ra',
              'condition': 'overcast-and-light-rain', 'wind_speed': 4.7, 'wind_gust': 11.9, 'wind_dir': 'sw',
              'pressure_mm': 729, 'pressure_pa': 972, 'humidity': 89, 'uv_index': 0, 'soil_temp': 14,
              'soil_moisture': 0.29, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 80},
             {'hour': '22', 'hour_ts': 1589310000, 'temp': 10, 'feels_like': 6, 'icon': 'ovc_-ra',
              'condition': 'overcast-and-light-rain', 'wind_speed': 5.5, 'wind_gust': 11.9, 'wind_dir': 'sw',
              'pressure_mm': 728, 'pressure_pa': 971, 'humidity': 89, 'uv_index': 0, 'soil_temp': 14,
              'soil_moisture': 0.29, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 80},
             {'hour': '23', 'hour_ts': 1589313600, 'temp': 9, 'feels_like': 4, 'icon': 'ovc_-ra',
              'condition': 'overcast-and-light-rain', 'wind_speed': 5.5, 'wind_gust': 11.9, 'wind_dir': 'sw',
              'pressure_mm': 728, 'pressure_pa': 971, 'humidity': 88, 'uv_index': 0, 'soil_temp': 14,
              'soil_moisture': 0.29, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 80}]},
        {'date': '2020-05-13', 'date_ts': 1589317200, 'week': 20, 'sunrise': '04:32', 'sunset': '20:31', 'moon_code': 3,
         'moon_text': 'decreasing-moon', 'parts': {
            'night': {'_source': '0,1,2,3,4,5', 'temp_min': 3, 'temp_max': 6, 'temp_avg': 5, 'feels_like': -2,
                      'icon': 'ovc_-ra', 'condition': 'overcast-and-light-rain', 'daytime': 'n', 'polar': False,
                      'wind_speed': 7.9, 'wind_gust': 16.2, 'wind_dir': 'w', 'pressure_mm': 733, 'pressure_pa': 978,
                      'humidity': 81, 'uv_index': 0, 'soil_temp': 10, 'soil_moisture': 0.29, 'prec_mm': 0.6,
                      'prec_period': 360, 'prec_prob': 60},
            'morning': {'_source': '6,7,8,9,10,11', 'temp_min': 3, 'temp_max': 9, 'temp_avg': 6, 'feels_like': -1,
                        'icon': 'bkn_d', 'condition': 'cloudy', 'daytime': 'd', 'polar': False, 'wind_speed': 7.5,
                        'wind_gust': 14.7, 'wind_dir': 'nw', 'pressure_mm': 739, 'pressure_pa': 986, 'humidity': 58,
                        'uv_index': 4, 'soil_temp': 8, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 360,
                        'prec_prob': 0},
            'day': {'_source': '12,13,14,15,16,17', 'temp_min': 10, 'temp_max': 12, 'temp_avg': 11, 'feels_like': 4,
                    'icon': 'bkn_d', 'condition': 'cloudy', 'daytime': 'd', 'polar': False, 'wind_speed': 7.7,
                    'wind_gust': 15.5, 'wind_dir': 'nw', 'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 37,
                    'uv_index': 5, 'soil_temp': 13, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 360,
                    'prec_prob': 0},
            'evening': {'_source': '18,19,20,21,22,23', 'temp_min': 8, 'temp_max': 11, 'temp_avg': 10, 'feels_like': 5,
                        'icon': 'ovc', 'condition': 'overcast', 'daytime': 'd', 'polar': False, 'wind_speed': 4.4,
                        'wind_gust': 10.3, 'wind_dir': 'w', 'pressure_mm': 744, 'pressure_pa': 992, 'humidity': 49,
                        'uv_index': 1, 'soil_temp': 11, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 360,
                        'prec_prob': 0},
            'day_short': {'_source': '8,9,10,11,12,13,14,15,16,17,18,19,20', 'temp': 12, 'temp_min': 5, 'feels_like': 5,
                          'icon': 'bkn_d', 'condition': 'cloudy', 'wind_speed': 7.7, 'wind_gust': 15.5,
                          'wind_dir': 'nw', 'pressure_mm': 741, 'pressure_pa': 988, 'humidity': 43, 'uv_index': 5,
                          'soil_temp': 12, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_prob': 0},
            'night_short': {'temp': 3, 'feels_like': -5, 'icon': 'ovc_-ra', 'condition': 'overcast-and-light-rain',
                            'wind_speed': 7.9, 'wind_gust': 16.2, 'wind_dir': 'w', 'pressure_mm': 733,
                            'pressure_pa': 978, 'humidity': 81, 'uv_index': 0, 'soil_temp': 10, 'soil_moisture': 0.29,
                            'prec_mm': 0.6, 'prec_prob': 60}}, 'hours': [
            {'hour': '0', 'hour_ts': 1589317200, 'temp': 6, 'feels_like': 0, 'icon': 'ovc_-ra',
             'condition': 'overcast-and-light-rain', 'wind_speed': 6, 'wind_gust': 14.9, 'wind_dir': 'w',
             'pressure_mm': 732, 'pressure_pa': 976, 'humidity': 82, 'uv_index': 0, 'soil_temp': 11,
             'soil_moisture': 0.29, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 60},
            {'hour': '1', 'hour_ts': 1589320800, 'temp': 4, 'feels_like': -2, 'icon': 'ovc_-ra',
             'condition': 'overcast-and-light-rain', 'wind_speed': 6.7, 'wind_gust': 14.9, 'wind_dir': 'w',
             'pressure_mm': 731, 'pressure_pa': 975, 'humidity': 83, 'uv_index': 0, 'soil_temp': 11,
             'soil_moisture': 0.29, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 60},
            {'hour': '2', 'hour_ts': 1589324400, 'temp': 3, 'feels_like': -4, 'icon': 'ovc_-ra',
             'condition': 'overcast-and-light-rain', 'wind_speed': 6.7, 'wind_gust': 14.9, 'wind_dir': 'w',
             'pressure_mm': 731, 'pressure_pa': 975, 'humidity': 83, 'uv_index': 0, 'soil_temp': 11,
             'soil_moisture': 0.29, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 60},
            {'hour': '3', 'hour_ts': 1589328000, 'temp': 3, 'feels_like': -4, 'icon': 'ovc_-ra',
             'condition': 'overcast-and-light-rain', 'wind_speed': 7.1, 'wind_gust': 16.2, 'wind_dir': 'nw',
             'pressure_mm': 735, 'pressure_pa': 980, 'humidity': 79, 'uv_index': 0, 'soil_temp': 8,
             'soil_moisture': 0.29, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 60},
            {'hour': '4', 'hour_ts': 1589331600, 'temp': 3, 'feels_like': -5, 'icon': 'ovc_-ra',
             'condition': 'overcast-and-light-rain', 'wind_speed': 7.9, 'wind_gust': 16.2, 'wind_dir': 'nw',
             'pressure_mm': 735, 'pressure_pa': 980, 'humidity': 79, 'uv_index': 0, 'soil_temp': 8,
             'soil_moisture': 0.29, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 60},
            {'hour': '5', 'hour_ts': 1589335200, 'temp': 3, 'feels_like': -5, 'icon': 'ovc_-ra',
             'condition': 'overcast-and-light-rain', 'wind_speed': 7.9, 'wind_gust': 16.2, 'wind_dir': 'nw',
             'pressure_mm': 735, 'pressure_pa': 980, 'humidity': 77, 'uv_index': 0, 'soil_temp': 8,
             'soil_moisture': 0.29, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 60},
            {'hour': '6', 'hour_ts': 1589338800, 'temp': 3, 'feels_like': -3, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 5.9, 'wind_gust': 12.4, 'wind_dir': 'nw', 'pressure_mm': 738, 'pressure_pa': 984,
             'humidity': 73, 'uv_index': 0, 'soil_temp': 7, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '7', 'hour_ts': 1589342400, 'temp': 4, 'feels_like': -3, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 7, 'wind_gust': 12.4, 'wind_dir': 'nw', 'pressure_mm': 737, 'pressure_pa': 983,
             'humidity': 68, 'uv_index': 0, 'soil_temp': 7, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '8', 'hour_ts': 1589346000, 'temp': 5, 'feels_like': -2, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 7.2, 'wind_gust': 12.4, 'wind_dir': 'nw', 'pressure_mm': 737, 'pressure_pa': 983,
             'humidity': 63, 'uv_index': 0, 'soil_temp': 7, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '9', 'hour_ts': 1589349600, 'temp': 6, 'feels_like': -1, 'icon': 'bkn_d', 'condition': 'cloudy',
             'wind_speed': 6.4, 'wind_gust': 14.7, 'wind_dir': 'nw', 'pressure_mm': 740, 'pressure_pa': 987,
             'humidity': 53, 'uv_index': 1, 'soil_temp': 9, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '10', 'hour_ts': 1589353200, 'temp': 8, 'feels_like': 1, 'icon': 'bkn_d', 'condition': 'cloudy',
             'wind_speed': 7.5, 'wind_gust': 14.7, 'wind_dir': 'nw', 'pressure_mm': 740, 'pressure_pa': 987,
             'humidity': 47, 'uv_index': 3, 'soil_temp': 9, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '11', 'hour_ts': 1589356800, 'temp': 9, 'feels_like': 2, 'icon': 'bkn_d', 'condition': 'cloudy',
             'wind_speed': 7.5, 'wind_gust': 14.7, 'wind_dir': 'nw', 'pressure_mm': 740, 'pressure_pa': 987,
             'humidity': 44, 'uv_index': 4, 'soil_temp': 9, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '12', 'hour_ts': 1589360400, 'temp': 10, 'feels_like': 4, 'icon': 'bkn_d', 'condition': 'cloudy',
             'wind_speed': 6.5, 'wind_gust': 15.5, 'wind_dir': 'nw', 'pressure_mm': 742, 'pressure_pa': 990,
             'humidity': 40, 'uv_index': 4, 'soil_temp': 12, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '13', 'hour_ts': 1589364000, 'temp': 10, 'feels_like': 3, 'icon': 'bkn_d', 'condition': 'cloudy',
             'wind_speed': 7.7, 'wind_gust': 15.5, 'wind_dir': 'nw', 'pressure_mm': 742, 'pressure_pa': 990,
             'humidity': 38, 'uv_index': 5, 'soil_temp': 12, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '14', 'hour_ts': 1589367600, 'temp': 11, 'feels_like': 4, 'icon': 'bkn_d', 'condition': 'cloudy',
             'wind_speed': 7.7, 'wind_gust': 15.5, 'wind_dir': 'nw', 'pressure_mm': 742, 'pressure_pa': 990,
             'humidity': 36, 'uv_index': 4, 'soil_temp': 12, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '15', 'hour_ts': 1589371200, 'temp': 12, 'feels_like': 6, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 5.5, 'wind_gust': 13.6, 'wind_dir': 'w', 'pressure_mm': 742, 'pressure_pa': 990,
             'humidity': 34, 'uv_index': 4, 'soil_temp': 13, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '16', 'hour_ts': 1589374800, 'temp': 12, 'feels_like': 5, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 6.4, 'wind_gust': 13.6, 'wind_dir': 'w', 'pressure_mm': 742, 'pressure_pa': 990,
             'humidity': 35, 'uv_index': 2, 'soil_temp': 13, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '17', 'hour_ts': 1589378400, 'temp': 11, 'feels_like': 4, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 6.2, 'wind_gust': 13.6, 'wind_dir': 'w', 'pressure_mm': 742, 'pressure_pa': 990,
             'humidity': 36, 'uv_index': 1, 'soil_temp': 13, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '18', 'hour_ts': 1589382000, 'temp': 11, 'feels_like': 6, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 4, 'wind_gust': 10.3, 'wind_dir': 'w', 'pressure_mm': 743, 'pressure_pa': 991,
             'humidity': 41, 'uv_index': 1, 'soil_temp': 12, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '19', 'hour_ts': 1589385600, 'temp': 11, 'feels_like': 6, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 4.4, 'wind_gust': 10.3, 'wind_dir': 'w', 'pressure_mm': 743, 'pressure_pa': 991,
             'humidity': 44, 'uv_index': 0, 'soil_temp': 12, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '20', 'hour_ts': 1589389200, 'temp': 9, 'feels_like': 4, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 4.1, 'wind_gust': 10.3, 'wind_dir': 'w', 'pressure_mm': 743, 'pressure_pa': 991,
             'humidity': 47, 'uv_index': 0, 'soil_temp': 12, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '21', 'hour_ts': 1589392800, 'temp': 9, 'feels_like': 5, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 2.2, 'wind_gust': 6.6, 'wind_dir': 'sw', 'pressure_mm': 744, 'pressure_pa': 992,
             'humidity': 49, 'uv_index': 0, 'soil_temp': 10, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '22', 'hour_ts': 1589396400, 'temp': 8, 'feels_like': 4, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 2.7, 'wind_gust': 6.6, 'wind_dir': 'sw', 'pressure_mm': 744, 'pressure_pa': 992,
             'humidity': 54, 'uv_index': 0, 'soil_temp': 10, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '23', 'hour_ts': 1589400000, 'temp': 8, 'feels_like': 4, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 2.7, 'wind_gust': 6.6, 'wind_dir': 'sw', 'pressure_mm': 744, 'pressure_pa': 992,
             'humidity': 56, 'uv_index': 0, 'soil_temp': 10, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0}]},
        {'date': '2020-05-14', 'date_ts': 1589403600, 'week': 20, 'sunrise': '04:30', 'sunset': '20:32', 'moon_code': 4,
         'moon_text': 'last-quarter', 'parts': {
            'night': {'_source': '0,1,2,3,4,5', 'temp_min': 7, 'temp_max': 7, 'temp_avg': 7, 'feels_like': 2,
                      'icon': 'ovc', 'condition': 'overcast', 'daytime': 'n', 'polar': False, 'wind_speed': 3.6,
                      'wind_gust': 8, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991, 'humidity': 58,
                      'uv_index': 0, 'soil_temp': 9, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 360,
                      'prec_prob': 0},
            'morning': {'_source': '6,7,8,9,10,11', 'temp_min': 7, 'temp_max': 11, 'temp_avg': 9, 'feels_like': 3,
                        'icon': 'ovc_-ra', 'condition': 'overcast-and-light-rain', 'daytime': 'd', 'polar': False,
                        'wind_speed': 5.9, 'wind_gust': 12.2, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991,
                        'humidity': 57, 'uv_index': 3, 'soil_temp': 9, 'soil_moisture': 0.27, 'prec_mm': 0.3,
                        'prec_period': 360, 'prec_prob': 50},
            'day': {'_source': '12,13,14,15,16,17', 'temp_min': 11, 'temp_max': 12, 'temp_avg': 12, 'feels_like': 8,
                    'icon': 'ovc', 'condition': 'overcast', 'daytime': 'd', 'polar': False, 'wind_speed': 4.6,
                    'wind_gust': 10.4, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991, 'humidity': 54,
                    'uv_index': 5, 'soil_temp': 12, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 360,
                    'prec_prob': 0},
            'evening': {'_source': '18,19,20,21,22,23', 'temp_min': 7, 'temp_max': 11, 'temp_avg': 9, 'feels_like': 6,
                        'icon': 'ovc_-ra', 'condition': 'overcast-and-light-rain', 'daytime': 'd', 'polar': False,
                        'wind_speed': 2.8, 'wind_gust': 9.2, 'wind_dir': 'sw', 'pressure_mm': 742, 'pressure_pa': 990,
                        'humidity': 75, 'uv_index': 1, 'soil_temp': 10, 'soil_moisture': 0.28, 'prec_mm': 0.6,
                        'prec_period': 360, 'prec_prob': 50},
            'day_short': {'_source': '8,9,10,11,12,13,14,15,16,17,18,19,20', 'temp': 12, 'temp_min': 9, 'feels_like': 7,
                          'icon': 'ovc_-ra', 'condition': 'overcast-and-light-rain', 'wind_speed': 5.9,
                          'wind_gust': 12.2, 'wind_dir': 'sw', 'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 58,
                          'uv_index': 3, 'soil_temp': 11, 'soil_moisture': 0.27, 'prec_mm': 0.6, 'prec_prob': 50},
            'night_short': {'temp': 7, 'feels_like': 2, 'icon': 'ovc', 'condition': 'overcast', 'wind_speed': 3.6,
                            'wind_gust': 8, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991, 'humidity': 58,
                            'uv_index': 0, 'soil_temp': 9, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_prob': 0}},
         'hours': [
             {'hour': '0', 'hour_ts': 1589403600, 'temp': 7, 'feels_like': 3, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 2.5, 'wind_gust': 5.9, 'wind_dir': 'sw', 'pressure_mm': 744, 'pressure_pa': 992,
              'humidity': 56, 'uv_index': 0, 'soil_temp': 9, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '1', 'hour_ts': 1589407200, 'temp': 7, 'feels_like': 3, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 3, 'wind_gust': 5.9, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991,
              'humidity': 58, 'uv_index': 0, 'soil_temp': 9, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '2', 'hour_ts': 1589410800, 'temp': 7, 'feels_like': 3, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 3, 'wind_gust': 5.9, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991,
              'humidity': 59, 'uv_index': 0, 'soil_temp': 9, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '3', 'hour_ts': 1589414400, 'temp': 7, 'feels_like': 3, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 3, 'wind_gust': 8, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991, 'humidity': 56,
              'uv_index': 0, 'soil_temp': 8, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60, 'prec_prob': 0},
             {'hour': '4', 'hour_ts': 1589418000, 'temp': 7, 'feels_like': 3, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 3.5, 'wind_gust': 8, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991,
              'humidity': 60, 'uv_index': 0, 'soil_temp': 8, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '5', 'hour_ts': 1589421600, 'temp': 7, 'feels_like': 2, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 3.6, 'wind_gust': 8, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991,
              'humidity': 59, 'uv_index': 0, 'soil_temp': 8, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '6', 'hour_ts': 1589425200, 'temp': 7, 'feels_like': 2, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 3.7, 'wind_gust': 9.6, 'wind_dir': 's', 'pressure_mm': 743, 'pressure_pa': 991,
              'humidity': 58, 'uv_index': 0, 'soil_temp': 8, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '7', 'hour_ts': 1589428800, 'temp': 8, 'feels_like': 3, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 4.5, 'wind_gust': 9.6, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991,
              'humidity': 58, 'uv_index': 1, 'soil_temp': 8, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '8', 'hour_ts': 1589432400, 'temp': 9, 'feels_like': 4, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 4.6, 'wind_gust': 9.6, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991,
              'humidity': 56, 'uv_index': 1, 'soil_temp': 8, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0}, {'hour': '9', 'hour_ts': 1589436000, 'temp': 10, 'feels_like': 5, 'icon': 'ovc_-ra',
                                'condition': 'overcast-and-light-rain', 'wind_speed': 4.8, 'wind_gust': 12.2,
                                'wind_dir': 'sw', 'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 57, 'uv_index': 2,
                                'soil_temp': 10, 'soil_moisture': 0.27, 'prec_mm': 0.1, 'prec_period': 60,
                                'prec_prob': 50},
             {'hour': '10', 'hour_ts': 1589439600, 'temp': 11, 'feels_like': 6, 'icon': 'ovc_-ra',
              'condition': 'overcast-and-light-rain', 'wind_speed': 5.9, 'wind_gust': 12.2, 'wind_dir': 'sw',
              'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 56, 'uv_index': 3, 'soil_temp': 10,
              'soil_moisture': 0.27, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 50},
             {'hour': '11', 'hour_ts': 1589443200, 'temp': 11, 'feels_like': 6, 'icon': 'ovc_-ra',
              'condition': 'overcast-and-light-rain', 'wind_speed': 5.8, 'wind_gust': 12.2, 'wind_dir': 'sw',
              'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 54, 'uv_index': 3, 'soil_temp': 10,
              'soil_moisture': 0.27, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 50},
             {'hour': '12', 'hour_ts': 1589446800, 'temp': 12, 'feels_like': 9, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 3.7, 'wind_gust': 8.5, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991,
              'humidity': 52, 'uv_index': 5, 'soil_temp': 11, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '13', 'hour_ts': 1589450400, 'temp': 12, 'feels_like': 8, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 4.6, 'wind_gust': 8.5, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991,
              'humidity': 51, 'uv_index': 5, 'soil_temp': 11, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '14', 'hour_ts': 1589454000, 'temp': 12, 'feels_like': 8, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 4.6, 'wind_gust': 8.5, 'wind_dir': 'sw', 'pressure_mm': 743, 'pressure_pa': 991,
              'humidity': 50, 'uv_index': 5, 'soil_temp': 11, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '15', 'hour_ts': 1589457600, 'temp': 12, 'feels_like': 9, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 3.8, 'wind_gust': 10.4, 'wind_dir': 'sw', 'pressure_mm': 742, 'pressure_pa': 990,
              'humidity': 55, 'uv_index': 4, 'soil_temp': 12, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '16', 'hour_ts': 1589461200, 'temp': 12, 'feels_like': 7, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 4.6, 'wind_gust': 10.4, 'wind_dir': 'sw', 'pressure_mm': 742, 'pressure_pa': 990,
              'humidity': 56, 'uv_index': 2, 'soil_temp': 12, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0},
             {'hour': '17', 'hour_ts': 1589464800, 'temp': 11, 'feels_like': 6, 'icon': 'ovc', 'condition': 'overcast',
              'wind_speed': 4.5, 'wind_gust': 10.4, 'wind_dir': 'sw', 'pressure_mm': 742, 'pressure_pa': 990,
              'humidity': 58, 'uv_index': 1, 'soil_temp': 12, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 60,
              'prec_prob': 0}, {'hour': '18', 'hour_ts': 1589468400, 'temp': 11, 'feels_like': 8, 'icon': 'ovc_-ra',
                                'condition': 'overcast-and-light-rain', 'wind_speed': 2.5, 'wind_gust': 9.2,
                                'wind_dir': 'sw', 'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 66, 'uv_index': 1,
                                'soil_temp': 11, 'soil_moisture': 0.27, 'prec_mm': 0.1, 'prec_period': 60,
                                'prec_prob': 50},
             {'hour': '19', 'hour_ts': 1589472000, 'temp': 10, 'feels_like': 7, 'icon': 'ovc_-ra',
              'condition': 'overcast-and-light-rain', 'wind_speed': 2.8, 'wind_gust': 9.2, 'wind_dir': 'sw',
              'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 69, 'uv_index': 0, 'soil_temp': 11,
              'soil_moisture': 0.27, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 50},
             {'hour': '20', 'hour_ts': 1589475600, 'temp': 9, 'feels_like': 6, 'icon': 'ovc_-ra',
              'condition': 'overcast-and-light-rain', 'wind_speed': 2.7, 'wind_gust': 9.2, 'wind_dir': 'sw',
              'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 71, 'uv_index': 0, 'soil_temp': 11,
              'soil_moisture': 0.27, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 50},
             {'hour': '21', 'hour_ts': 1589479200, 'temp': 7, 'feels_like': 5, 'icon': 'ovc_-ra',
              'condition': 'overcast-and-light-rain', 'wind_speed': 0.9, 'wind_gust': 5.3, 'wind_dir': 's',
              'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 78, 'uv_index': 0, 'soil_temp': 9,
              'soil_moisture': 0.28, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 40},
             {'hour': '22', 'hour_ts': 1589482800, 'temp': 7, 'feels_like': 5, 'icon': 'ovc_-ra',
              'condition': 'overcast-and-light-rain', 'wind_speed': 1.2, 'wind_gust': 5.3, 'wind_dir': 's',
              'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 81, 'uv_index': 0, 'soil_temp': 9,
              'soil_moisture': 0.28, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 40},
             {'hour': '23', 'hour_ts': 1589486400, 'temp': 7, 'feels_like': 5, 'icon': 'ovc_-ra',
              'condition': 'overcast-and-light-rain', 'wind_speed': 1.2, 'wind_gust': 5.3, 'wind_dir': 's',
              'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 82, 'uv_index': 0, 'soil_temp': 9,
              'soil_moisture': 0.28, 'prec_mm': 0.1, 'prec_period': 60, 'prec_prob': 40}]},
        {'date': '2020-05-15', 'date_ts': 1589490000, 'week': 20, 'sunrise': '04:29', 'sunset': '20:34', 'moon_code': 4,
         'moon_text': 'last-quarter', 'parts': {
            'night': {'_source': '0,1,2,3,4,5', 'temp_min': 5, 'temp_max': 6, 'temp_avg': 6, 'feels_like': 4,
                      'icon': 'ovc_-ra', 'condition': 'overcast-and-light-rain', 'daytime': 'n', 'polar': False,
                      'wind_speed': 0.8, 'wind_gust': 2.2, 'wind_dir': 'se', 'pressure_mm': 742, 'pressure_pa': 990,
                      'humidity': 88, 'uv_index': 0, 'soil_temp': 8, 'soil_moisture': 0.29, 'prec_mm': 0.9,
                      'prec_period': 360, 'prec_prob': 60},
            'morning': {'_source': '6,7,8,9,10,11', 'temp_min': 5, 'temp_max': 10, 'temp_avg': 8, 'feels_like': 5,
                        'icon': 'ovc', 'condition': 'overcast', 'daytime': 'd', 'polar': False, 'wind_speed': 3.5,
                        'wind_gust': 9.7, 'wind_dir': 'nw', 'pressure_mm': 741, 'pressure_pa': 988, 'humidity': 70,
                        'uv_index': 4, 'soil_temp': 8, 'soil_moisture': 0.3, 'prec_mm': 0, 'prec_period': 360,
                        'prec_prob': 0},
            'day': {'_source': '12,13,14,15', 'temp_min': 11, 'temp_max': 12, 'temp_avg': 12, 'feels_like': 7,
                    'icon': 'bkn_d', 'condition': 'cloudy', 'daytime': 'd', 'polar': False, 'wind_speed': 5.2,
                    'wind_gust': 13.3, 'wind_dir': 'nw', 'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 40,
                    'uv_index': 5, 'soil_temp': 12, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 360,
                    'prec_prob': 0},
            'evening': {'_source': '18,21', 'temp_min': 9, 'temp_max': 12, 'temp_avg': 11, 'feels_like': 7,
                        'icon': 'ovc', 'condition': 'overcast', 'daytime': 'd', 'polar': False, 'wind_speed': 3.6,
                        'wind_gust': 7.8, 'wind_dir': 'nw', 'pressure_mm': 743, 'pressure_pa': 991, 'humidity': 50,
                        'uv_index': 1, 'soil_temp': 11, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 360,
                        'prec_prob': 0},
            'day_short': {'_source': '8,9,10,11,12,13,14,15,18', 'temp': 12, 'temp_min': 7, 'feels_like': 8,
                          'icon': 'bkn_d', 'condition': 'cloudy', 'wind_speed': 5.2, 'wind_gust': 13.3,
                          'wind_dir': 'nw', 'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 51, 'uv_index': 5,
                          'soil_temp': 12, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_prob': 0},
            'night_short': {'temp': 5, 'feels_like': 3, 'icon': 'ovc_-ra', 'condition': 'overcast-and-light-rain',
                            'wind_speed': 0.8, 'wind_gust': 2.2, 'wind_dir': 'se', 'pressure_mm': 742,
                            'pressure_pa': 990, 'humidity': 88, 'uv_index': 0, 'soil_temp': 8, 'soil_moisture': 0.29,
                            'prec_mm': 0.9, 'prec_prob': 60}}, 'hours': [
            {'hour': '0', 'hour_ts': 1589490000, 'temp': 6, 'feels_like': 4, 'icon': 'ovc_-ra',
             'condition': 'overcast-and-light-rain', 'wind_speed': 0.5, 'wind_gust': 2.2, 'wind_dir': 'se',
             'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 84, 'uv_index': 0, 'soil_temp': 8,
             'soil_moisture': 0.28, 'prec_mm': 0.3, 'prec_period': 60, 'prec_prob': 60},
            {'hour': '1', 'hour_ts': 1589493600, 'temp': 6, 'feels_like': 4, 'icon': 'ovc_-ra',
             'condition': 'overcast-and-light-rain', 'wind_speed': 0.5, 'wind_gust': 2.2, 'wind_dir': 'se',
             'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 87, 'uv_index': 0, 'soil_temp': 8,
             'soil_moisture': 0.28, 'prec_mm': 0.3, 'prec_period': 60, 'prec_prob': 60},
            {'hour': '2', 'hour_ts': 1589497200, 'temp': 6, 'feels_like': 4, 'icon': 'ovc_-ra',
             'condition': 'overcast-and-light-rain', 'wind_speed': 0.5, 'wind_gust': 2.2, 'wind_dir': 'se',
             'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 88, 'uv_index': 0, 'soil_temp': 8,
             'soil_moisture': 0.28, 'prec_mm': 0.3, 'prec_period': 60, 'prec_prob': 60},
            {'hour': '3', 'hour_ts': 1589500800, 'temp': 5, 'feels_like': 3, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 0.6, 'wind_gust': 1.7, 'wind_dir': 'n', 'pressure_mm': 741, 'pressure_pa': 988,
             'humidity': 88, 'uv_index': 0, 'soil_temp': 7, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '4', 'hour_ts': 1589504400, 'temp': 5, 'feels_like': 3, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 0.8, 'wind_gust': 1.7, 'wind_dir': 'n', 'pressure_mm': 741, 'pressure_pa': 988,
             'humidity': 89, 'uv_index': 0, 'soil_temp': 7, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '5', 'hour_ts': 1589508000, 'temp': 5, 'feels_like': 3, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 0.8, 'wind_gust': 1.7, 'wind_dir': 'n', 'pressure_mm': 741, 'pressure_pa': 988,
             'humidity': 89, 'uv_index': 0, 'soil_temp': 7, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '6', 'hour_ts': 1589511600, 'temp': 5, 'feels_like': 3, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 1.1, 'wind_gust': 4, 'wind_dir': 'nw', 'pressure_mm': 741, 'pressure_pa': 988,
             'humidity': 85, 'uv_index': 0, 'soil_temp': 7, 'soil_moisture': 0.3, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '7', 'hour_ts': 1589515200, 'temp': 6, 'feels_like': 3, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 1.5, 'wind_gust': 4, 'wind_dir': 'nw', 'pressure_mm': 741, 'pressure_pa': 988,
             'humidity': 81, 'uv_index': 1, 'soil_temp': 7, 'soil_moisture': 0.3, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '8', 'hour_ts': 1589518800, 'temp': 7, 'feels_like': 4, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 1.6, 'wind_gust': 4, 'wind_dir': 'nw', 'pressure_mm': 741, 'pressure_pa': 988,
             'humidity': 75, 'uv_index': 1, 'soil_temp': 7, 'soil_moisture': 0.3, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '9', 'hour_ts': 1589522400, 'temp': 8, 'feels_like': 4, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 2.7, 'wind_gust': 9.7, 'wind_dir': 'nw', 'pressure_mm': 741, 'pressure_pa': 988,
             'humidity': 65, 'uv_index': 2, 'soil_temp': 9, 'soil_moisture': 0.3, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '10', 'hour_ts': 1589526000, 'temp': 9, 'feels_like': 5, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 3.5, 'wind_gust': 9.7, 'wind_dir': 'nw', 'pressure_mm': 741, 'pressure_pa': 988,
             'humidity': 59, 'uv_index': 3, 'soil_temp': 9, 'soil_moisture': 0.3, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '11', 'hour_ts': 1589529600, 'temp': 10, 'feels_like': 7, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 3.5, 'wind_gust': 9.7, 'wind_dir': 'nw', 'pressure_mm': 741, 'pressure_pa': 988,
             'humidity': 55, 'uv_index': 4, 'soil_temp': 9, 'soil_moisture': 0.3, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '12', 'hour_ts': 1589533200, 'temp': 11, 'feels_like': 6, 'icon': 'bkn_d', 'condition': 'cloudy',
             'wind_speed': 4.4, 'wind_gust': 12.7, 'wind_dir': 'nw', 'pressure_mm': 742, 'pressure_pa': 990,
             'humidity': 41, 'uv_index': 4, 'soil_temp': 12, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '13', 'hour_ts': 1589536800, 'temp': 12, 'feels_like': 7, 'icon': 'bkn_d', 'condition': 'cloudy',
             'wind_speed': 5.2, 'wind_gust': 12.7, 'wind_dir': 'nw', 'pressure_mm': 742, 'pressure_pa': 990,
             'humidity': 39, 'uv_index': 5, 'soil_temp': 12, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '14', 'hour_ts': 1589540400, 'temp': 12, 'feels_like': 7, 'icon': 'bkn_d', 'condition': 'cloudy',
             'wind_speed': 5.2, 'wind_gust': 12.7, 'wind_dir': 'nw', 'pressure_mm': 742, 'pressure_pa': 990,
             'humidity': 38, 'uv_index': 4, 'soil_temp': 12, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0},
            {'hour': '15', 'hour_ts': 1589544000, 'temp': 12, 'feels_like': 7, 'icon': 'ovc', 'condition': 'overcast',
             'wind_speed': 4.8, 'wind_gust': 13.3, 'wind_dir': 'nw', 'pressure_mm': 742, 'pressure_pa': 990,
             'humidity': 41, 'uv_index': 4, 'soil_temp': 13, 'soil_moisture': 0.29, 'prec_mm': 0, 'prec_period': 60,
             'prec_prob': 0}]},
        {'date': '2020-05-16', 'date_ts': 1589576400, 'week': 20, 'sunrise': '04:27', 'sunset': '20:36', 'moon_code': 5,
         'moon_text': 'decreasing-moon', 'parts': {
            'night': {'_source': '0,3', 'temp_min': 3, 'temp_max': 5, 'temp_avg': 4, 'feels_like': 1, 'icon': 'bkn_n',
                      'condition': 'cloudy', 'daytime': 'n', 'polar': False, 'wind_speed': 1.2, 'wind_gust': 3.4,
                      'wind_dir': 'nw', 'pressure_mm': 745, 'pressure_pa': 994, 'humidity': 70, 'uv_index': 0,
                      'soil_temp': 7, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 360, 'prec_prob': 0},
            'morning': {'_source': '6,9', 'temp_min': 5, 'temp_max': 11, 'temp_avg': 8, 'feels_like': 5, 'icon': 'ovc',
                        'condition': 'overcast', 'daytime': 'd', 'polar': False, 'wind_speed': 1.4, 'wind_gust': 5.6,
                        'wind_dir': 'w', 'pressure_mm': 745, 'pressure_pa': 994, 'humidity': 60, 'uv_index': 2,
                        'soil_temp': 8, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 360, 'prec_prob': 0},
            'day': {'_source': '12,15', 'temp_min': 13, 'temp_max': 14, 'temp_avg': 14, 'feels_like': 11, 'icon': 'ovc',
                    'condition': 'overcast', 'daytime': 'd', 'polar': False, 'wind_speed': 3, 'wind_gust': 9.2,
                    'wind_dir': 'w', 'pressure_mm': 744, 'pressure_pa': 992, 'humidity': 37, 'uv_index': 5,
                    'soil_temp': 12, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_period': 360, 'prec_prob': 0},
            'evening': {'_source': '18,21', 'temp_min': 11, 'temp_max': 14, 'temp_avg': 13, 'feels_like': 10,
                        'icon': 'bkn_d', 'condition': 'cloudy', 'daytime': 'd', 'polar': False, 'wind_speed': 2.3,
                        'wind_gust': 6.9, 'wind_dir': 'w', 'pressure_mm': 744, 'pressure_pa': 992, 'humidity': 47,
                        'soil_temp': 11, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 360, 'prec_prob': 0},
            'day_short': {'_source': '9,12,15,18', 'temp': 14, 'temp_min': 11, 'feels_like': 11, 'icon': 'ovc',
                          'condition': 'overcast', 'wind_speed': 3, 'wind_gust': 9.2, 'wind_dir': 'w',
                          'pressure_mm': 744, 'pressure_pa': 992, 'humidity': 41, 'uv_index': 5, 'soil_temp': 12,
                          'soil_moisture': 0.28, 'prec_mm': 0, 'prec_prob': 0},
            'night_short': {'temp': 3, 'feels_like': 0, 'icon': 'bkn_n', 'condition': 'cloudy', 'wind_speed': 1.2,
                            'wind_gust': 3.4, 'wind_dir': 'nw', 'pressure_mm': 745, 'pressure_pa': 994, 'humidity': 70,
                            'uv_index': 0, 'soil_temp': 7, 'soil_moisture': 0.28, 'prec_mm': 0, 'prec_prob': 0}},
         'hours': []},
        {'date': '2020-05-17', 'date_ts': 1589662800, 'week': 20, 'sunrise': '04:25', 'sunset': '20:37', 'moon_code': 5,
         'moon_text': 'decreasing-moon', 'parts': {
            'night': {'_source': '0,3', 'temp_min': 7, 'temp_max': 8, 'temp_avg': 8, 'feels_like': 5, 'icon': 'ovc',
                      'condition': 'overcast', 'daytime': 'n', 'polar': False, 'wind_speed': 1.9, 'wind_gust': 5.9,
                      'wind_dir': 'sw', 'pressure_mm': 744, 'pressure_pa': 992, 'humidity': 63, 'soil_temp': 8,
                      'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 360, 'prec_prob': 0},
            'morning': {'_source': '6,9', 'temp_min': 8, 'temp_max': 12, 'temp_avg': 10, 'feels_like': 6, 'icon': 'ovc',
                        'condition': 'overcast', 'daytime': 'd', 'polar': False, 'wind_speed': 4, 'wind_gust': 10.1,
                        'wind_dir': 'w', 'pressure_mm': 744, 'pressure_pa': 992, 'humidity': 61, 'soil_temp': 9,
                        'soil_moisture': 0.27, 'prec_mm': 0, 'prec_period': 360, 'prec_prob': 0},
            'day': {'_source': '12,15', 'temp_min': 14, 'temp_max': 15, 'temp_avg': 15, 'feels_like': 10,
                    'icon': 'ovc_-ra', 'condition': 'overcast-and-light-rain', 'daytime': 'd', 'polar': False,
                    'wind_speed': 4.7, 'wind_gust': 12, 'wind_dir': 'w', 'pressure_mm': 744, 'pressure_pa': 992,
                    'humidity': 47, 'soil_temp': 14, 'soil_moisture': 0.26, 'prec_mm': 0.2, 'prec_period': 360,
                    'prec_prob': 50},
            'evening': {'_source': '18,21', 'temp_min': 12, 'temp_max': 14, 'temp_avg': 13, 'feels_like': 9,
                        'icon': 'ovc', 'condition': 'overcast', 'daytime': 'd', 'polar': False, 'wind_speed': 3.3,
                        'wind_gust': 9, 'wind_dir': 'w', 'pressure_mm': 743, 'pressure_pa': 991, 'humidity': 51,
                        'soil_temp': 12, 'soil_moisture': 0.26, 'prec_mm': 0, 'prec_period': 360, 'prec_prob': 0},
            'day_short': {'_source': '9,12,15,18', 'temp': 15, 'temp_min': 12, 'feels_like': 10, 'icon': 'ovc_-ra',
                          'condition': 'overcast-and-light-rain', 'wind_speed': 4.7, 'wind_gust': 12, 'wind_dir': 'w',
                          'pressure_mm': 744, 'pressure_pa': 992, 'humidity': 49, 'soil_temp': 13,
                          'soil_moisture': 0.26, 'prec_mm': 0.2, 'prec_prob': 50},
            'night_short': {'temp': 7, 'feels_like': 4, 'icon': 'ovc', 'condition': 'overcast', 'wind_speed': 1.9,
                            'wind_gust': 5.9, 'wind_dir': 'sw', 'pressure_mm': 744, 'pressure_pa': 992, 'humidity': 63,
                            'soil_temp': 8, 'soil_moisture': 0.27, 'prec_mm': 0, 'prec_prob': 0}}, 'hours': []},
        {'date': '2020-05-18', 'date_ts': 1589749200, 'week': 21, 'sunrise': '04:24', 'sunset': '20:39', 'moon_code': 6,
         'moon_text': 'decreasing-moon', 'parts': {
            'night': {'_source': '0,3', 'temp_min': 9, 'temp_max': 11, 'temp_avg': 10, 'feels_like': 7, 'icon': 'ovc',
                      'condition': 'overcast', 'daytime': 'n', 'polar': False, 'wind_speed': 2, 'wind_gust': 8,
                      'wind_dir': 'sw', 'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 68, 'soil_temp': 10,
                      'soil_moisture': 0.26, 'prec_mm': 0, 'prec_period': 360, 'prec_prob': 0},
            'morning': {'_source': '6,9', 'temp_min': 9, 'temp_max': 13, 'temp_avg': 11, 'feels_like': 8,
                        'icon': 'ovc_-ra', 'condition': 'overcast-and-light-rain', 'daytime': 'd', 'polar': False,
                        'wind_speed': 3.2, 'wind_gust': 14.4, 'wind_dir': 'sw', 'pressure_mm': 740, 'pressure_pa': 987,
                        'humidity': 70, 'soil_temp': 11, 'soil_moisture': 0.26, 'prec_mm': 0.6, 'prec_period': 360,
                        'prec_prob': 60},
            'day': {'_source': '12,15', 'temp_min': 14, 'temp_max': 14, 'temp_avg': 14, 'feels_like': 10,
                    'icon': 'ovc_-ra', 'condition': 'overcast-and-light-rain', 'daytime': 'd', 'polar': False,
                    'wind_speed': 4.1, 'wind_gust': 14.4, 'wind_dir': 'sw', 'pressure_mm': 738, 'pressure_pa': 984,
                    'humidity': 60, 'soil_temp': 12, 'soil_moisture': 0.27, 'prec_mm': 0.7, 'prec_period': 360,
                    'prec_prob': 70},
            'evening': {'_source': '18,21', 'temp_min': 10, 'temp_max': 13, 'temp_avg': 12, 'feels_like': 8,
                        'icon': 'ovc_-ra', 'condition': 'overcast-and-light-rain', 'daytime': 'd', 'polar': False,
                        'wind_speed': 3.8, 'wind_gust': 10.3, 'wind_dir': 'w', 'pressure_mm': 738, 'pressure_pa': 984,
                        'humidity': 67, 'soil_temp': 10, 'soil_moisture': 0.29, 'prec_mm': 0.3, 'prec_period': 360,
                        'prec_prob': 50},
            'day_short': {'_source': '9,12,15,18', 'temp': 14, 'temp_min': 13, 'feels_like': 10, 'icon': 'ovc_-ra',
                          'condition': 'overcast-and-light-rain', 'wind_speed': 4.1, 'wind_gust': 14.4,
                          'wind_dir': 'sw', 'pressure_mm': 738, 'pressure_pa': 984, 'humidity': 62, 'soil_temp': 12,
                          'soil_moisture': 0.27, 'prec_mm': 1.4, 'prec_prob': 70},
            'night_short': {'temp': 9, 'feels_like': 6, 'icon': 'ovc', 'condition': 'overcast', 'wind_speed': 2,
                            'wind_gust': 8, 'wind_dir': 'sw', 'pressure_mm': 742, 'pressure_pa': 990, 'humidity': 68,
                            'soil_temp': 10, 'soil_moisture': 0.26, 'prec_mm': 0, 'prec_prob': 0}}, 'hours': []}]}
